# Generated by Django 2.1.3 on 2018-11-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battlename', models.TextField(blank=True, db_column='battleName', null=True, unique=True)),
                ('battleyr', models.IntegerField(blank=True, db_column='battleYr', null=True)),
            ],
            options={
                'db_table': 'Battles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.TextField(blank=True, db_column='className', null=True, unique=True)),
                ('typeclass', models.CharField(blank=True, db_column='typeClass', max_length=2, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('numguns', models.IntegerField(blank=True, db_column='numGuns', null=True)),
                ('bore', models.IntegerField(blank=True, null=True)),
                ('displacement', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Outcomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship', models.TextField(blank=True, null=True)),
                ('battle', models.TextField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Outcomes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipname', models.TextField(blank=True, db_column='shipName', null=True, unique=True)),
                ('shipclass', models.TextField(blank=True, db_column='shipClass', null=True)),
                ('launchyr', models.IntegerField(blank=True, db_column='launchYr', null=True)),
            ],
            options={
                'db_table': 'Ships',
                'managed': False,
            },
        ),
    ]
