# Generated by Django 2.1.3 on 2018-11-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vBattle',
            fields=[
                ('battleyr', models.IntegerField(db_column='battleYr')),
                ('battlename', models.CharField(db_column='battleName', max_length=20, primary_key=True, serialize=False)),
                ('shipname', models.CharField(db_column='shipName', max_length=20)),
                ('outcome', models.CharField(blank=True, db_column='outcome', max_length=10, null=True)),
            ],
            options={
                'db_table': 'vBattle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='vShipClass',
            fields=[
                ('country', models.CharField(db_column='country', max_length=15)),
                ('shipname', models.CharField(db_column='shipName', max_length=20, primary_key=True, serialize=False)),
                ('launchyr', models.IntegerField(db_column='launchYr')),
                ('classname', models.CharField(db_column='className', max_length=20)),
                ('typeclass', models.CharField(db_column='typeClass', max_length=2)),
                ('numguns', models.IntegerField(db_column='numGuns')),
                ('bore', models.IntegerField(db_column='bore')),
                ('displacement', models.IntegerField(db_column='displacement')),
                ('outcome', models.CharField(blank=True, db_column='outcome', max_length=10, null=True)),
            ],
            options={
                'db_table': 'vShipClass',
                'managed': False,
            },
        ),
    ]
