# Generated by Django 2.1.3 on 2018-11-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0002_vbattle_vshipclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipslog',
            fields=[
                ('inserted', models.DateTimeField(primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, max_length=32, null=True)),
                ('exceptxt', models.CharField(blank=True, max_length=255, null=True)),
                ('querytxt', models.CharField(blank=True, max_length=255, null=True)),
                ('msgtxt', models.CharField(blank=True, max_length=255, null=True)),
                ('key1', models.CharField(blank=True, max_length=32, null=True)),
                ('val1', models.CharField(blank=True, max_length=32, null=True)),
                ('key2', models.CharField(blank=True, max_length=32, null=True)),
                ('val2', models.CharField(blank=True, max_length=32, null=True)),
                ('key3', models.CharField(blank=True, max_length=32, null=True)),
                ('val3', models.CharField(blank=True, max_length=32, null=True)),
                ('key4', models.CharField(blank=True, max_length=32, null=True)),
                ('val4', models.CharField(blank=True, max_length=32, null=True)),
                ('key5', models.CharField(blank=True, max_length=32, null=True)),
                ('val5', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'ShipsLog',
                'managed': True,
            },
        ),
    ]
