# Generated by Django 2.1.3 on 2018-11-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0004_auto_20181112_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipslog',
            name='inserted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
