# Generated by Django 2.1.3 on 2018-11-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0005_auto_20181112_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipslog',
            options={'get_latest_by': 'logid', 'managed': True},
        ),
    ]
