# Generated by Django 2.1.3 on 2018-11-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0006_auto_20181113_0633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipslog',
            options={'get_latest_by': 'logid', 'managed': True, 'ordering': ['-logid']},
        ),
    ]
